apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed-app
  labels:
    app: udagram-api-feed-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed-app
  template:
    metadata:
      labels:
        app: udagram-api-feed-app
    spec:
      containers:
      - name: udagram-api-feed
        image: minhtri188/udagram-api-feed
        ports:
        - containerPort: 8080
        env:
          # Define the environment variable
          - name: POSTGRES_HOST # Notice that this name here can different from the key name in the ConfigMap.
            valueFrom:
              configMapKeyRef:
                name: env-configmap   # The ConfigMap name.
                key: POSTGRES_HOST                    # The key to fetch from ConfigMap.
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_DB
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: AWS_PROFILE
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: URL

          - name: POSTGRES_USERNAME
            valueFrom:
                secretKeyRef:
                    name: env-secret
                    key: POSTGRES_USERNAME
                    optional: false # same as default; "xxx" must exist and include a key named "xxx"
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: env-secret
                    key: POSTGRES_PASSWORD
                    optional: false
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                    name: env-secret
                    key: JWT_SECRET
                    optional: false

          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                    name: aws-secret
                    key: AWS_ACCESS_KEY_ID
                    optional: false
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                    name: aws-secret
                    key: AWS_SECRET_ACCESS_KEY
                    optional: false